# Generated by Django 4.2.4 on 2023-12-07 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_alter_delivery_cook_alter_delivery_courier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "permissions": [
                    ("change_cook_delivery", "Can change the cook of the delivery")
                ]
            },
        ),
    ]
