# Generated by Django 4.2.4 on 2023-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="salt",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="courier",
            name="salt",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="manager",
            name="salt",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
