# Generated by Django 4.2.4 on 2023-12-01 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_client_salt_courier_salt_manager_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="salt",
        ),
    ]
