# Generated by Django 4.2.4 on 2023-12-07 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_cook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="qr_code",
        ),
    ]
